### ISSUE TITLE
Confusion on how to place strip test

### ISSUE THREAD

**Issue by janagombitova** [ternup/caddisfly-app#134]
# Context

I was testing Flow today and ran a few Caddisfly tests as part of a Flow form and noticed one thing. When I followed the step to place the strip test on the black bar on the colour card I did not know how to place it: with the strips on the left or on the right. 

I placed them on the right and then received a No result page even thought I followed all the steps the app told me.

![screenshot_2017-09-21-11-31-22](https://user-images.githubusercontent.com/12456965/30689824-6cf239c2-9ec2-11e7-9718-ff109aa99659.png)

I used the Caddisfly app version: 1.0.0 Beta 8.5 version

# Problem and opportunity 
It is unclear to the user on how to place the strip on the card and disappointing after following all the steps, you do not get a result because you placed the strip the other way around. 

# Next steps 
I am not sure if this is already changed in the newer versions of the app, but I would suggest to explore how to make it more explicit to the user on how to place the strip on the card.

**Comment by arthurakvo** [comment]
Hi Jana,

Thanks for this. In the new app that will be released in a couple of days the user is instructed both by text and a picture to place the test strips facing left on the Colour Reference Card (see the image here below). Besides this we are also considering to print the instruction to place the test strip facing left on the actual Colour Reference Card, but this is still up for discussion. 

@mtwestra correct?

![screenshot_20170921-100742](https://user-images.githubusercontent.com/29979018/30690990-aa265538-9eb5-11e7-8f5c-c18ee7643015.png)

**Comment by janagombitova** [comment]
@arthurakvo will this image be part of the user test workflow or only the instructions? As I personally never look at the instructions as I expect the app to navigate me in what I need to do. Secondly, I think image should be self explanatory enough, users in general do not tend to read text

**Comment by arthurakvo** [comment]
@janagombitova 

The text to place the test strip facing left is already included in the user test workflow. But there is no place to include the picture there. The placing of the test strip left is included in all training materials, included in the test strips instructions (text and picture) in the app and also as text in the user test workflow in the app. Working with hardware always means you have to read the instructions well the first and possibility second time you perform a test, this is something that we always stress in trainings and is definitely not too much to ask from an enumerator. The test instructions should indeed be self explanatory but they also should always be optional since users will perform a lot a test and should not be bothered with the full testing instructions every time they perform a test. 

@mtwestra @nhternup  What do you guys think?

**Comment by janagombitova** [comment]
I agree on the fact that working with hardware you need to read instructions, but the stript tests experience should be as simple as possible and the app should walk you through what you need to do as you do it, in my opinion. 

Personally I believe that software should be so understandable it does not need training and it is something we should strive for. Thus I would suggest to review the overall user experience of the Caddisfly app in the future with the design team to make it simple.

**Comment by nhternup** [comment]
This issue was also brought up earlier in https://github.com/akvo/akvo-caddisfly/issues/50 and definitely needs to be given higher priority as more users start to use the app. As mentioned there the quality checks could be improved to detect if the strip was placed incorrectly. A new version of the strip test is being worked on and this would likely be an important feature to include in it.

Further the 'no result' message could be improved to provide some help on why the test may have failed.

**Comment by mtwestra** [comment]
@janagombitova and @nhternup,

The next batch of color cards that we will print will have a drawing on it that explains how to place the strip. That should help.

**Comment by janagombitova** [comment]
We have updated the instruction and added them as part of the direct testing workflow with v. 1.0.11 that we assume will mitigate this issue.
