### ISSUE TITLE
Count down sometimes appears with test and sometimes not

### ISSUE THREAD

**Issue by janagombitova** [ternup/caddisfly-app#136]
Another issue I noticed when testing the pH HACH test in the 1.0.0 Beta 9 Test 2 version of the app is that I sometimes get the count down clock (10s) and sometimes I do not with the same test type.

**Comment by nhternup** [comment]
This is expected behaviour. As the patch has to be analysed 15 seconds after dipping, the countdown starts internally as soon as the start button is pressed. If the 15 seconds are used up by the quality check, the patch is analysed immediately without waiting any longer, in which case the countdown timer will not get displayed. If the quality check happens sooner, then the timer shows up counting down the remaining time.

**Comment by nhternup** [comment]
Marked as expected behaviour. Can be reopened if further discussion is necessary.
