### ISSUE TITLE
Cannot proceed with testing e.Coli

### ISSUE THREAD

**Issue by janagombitova** [ternup/caddisfly-app#235]
Francis reported an issue on the latest Cadidslfy app: 

I have an issue with caddisfly, some phones are not completing the process. once we select the compartment colour they just go back to "go to test" without even adding results. We have upgraded the software and some phone is okay. some are not working. We are using Samsung Galaxy J1 ace. When taking a picture in the E. coli test in Caddisfly the app stops working and you are redirected to the home screen of the smartphone.

The issues are:

- when taking a picture in the CBT test in Caddisfly (redirected to the home screen) and gives the message that caddisfly stopped working
- when submitting the result in the Caddisfly app (redirected to the Akvo Flow app 'Go to test' screen and result is not saved in Flow).

**Comment by nhternup** [comment]
This could be due to a low memory issue. In such a situation Android closes activities that are in the background. 

In this case it is possible that the Flow app activity is closed to make space for the Camera app. When Caddisfly returns the result, the Flow app cannot save the result as the launched question details may not be available anymore. 

Flow app would need to be updated to save its state when closed and the same state later restored when activated again such that launched question details are available when it receives the results.

**Comment by janagombitova** [comment]
Are there any checks we can de before allowing the user to perform a test to ensure there is enough space and no issues will arise down the line?

**Comment by nhternup** [comment]
There is no way to check the memory usage as that changes frequently based on background services running. Which activity gets killed in such situations is controlled by Android OS. 

The recommended method in this case is to save and restore the state of the activity.

btw. On looking up the specifications for J1 Ace, it seems to have less than 1 GB RAM as compared to at least 2 GB memory in most modern phones.

**Comment by janagombitova** [comment]
Released in 1.0.10
