### ISSUE TITLE
Adding Total Coliform to the Compartment Bag Test 

### ISSUE THREAD

**Issue by MBlommestijn** [ternup/caddisfly-app#236]
The Aquagenx CBT now also includes a Total Coliform result by using a UV Flashlight.
https://www.aquagenx.com/cbt-ectc/

In Akvo Caddisfly, it should be possible to select four different test options for the Compartment Bag Test (Coliform), tests 3 and 4 need to be added:
1. E. coli (0-100 MPN)
2. E. coli (0-1000 MPN)
3. E. coli (0-100 MPN) + Total Coliform (0-100 MPN)
4. E. coli (0-1000 MPN) + Total Coliform (0-1000 MPN)

Both E. coli and Total Coliform presence/absence are scored based on the same MPN table.
In test options 3 & 4 two interface results have to be submitted, one for E. coli and one for Total Coliform.

See also the CBT EC+TC instructions:
https://www.aquagenx.com/wp-content/uploads/2019/06/MPN-CBT-ECTC-Instructions-DrinkingWater-June2019.pdf

**Comment by janagombitova** [comment]
Today Mert and I connected on this issue to talk implementation, user workflow and why we are adding it in the first place. We agreed on the following: 

# Possible user workflow 
The idea is to keep the current E.coli tests untouched, so if you are only interested in testing this, nothing changes. 

Here is a possible implementation workflow (still need more info on how the test works and who uses it for what purpose to further clarify and decide) 

We add two extra tests that include Total Coliform. In this case Al will: 
1. Complete the e.coli steps, click the UI with the compartments to indicate which have a different colour
2. See results and calculated values and risk categories 
3. See a few instructions next for the Total Coliform 
4. Click the UI with the compartments to indicate which have a different colour 
5. See the result (Mert will provide) 
6. *optional* summary page with e.coli and total coliform result
7. Go back to Flow where both results are saved. 

We were considering combining the results and the UI selection of the compartments into one screen but then learned that WHO does not have a standard on how to evaluate total coliform values. Considering we follow a WHO standard for e.coli results, we did not want to combine the two to create confusion. 

# Next steps 
When further researching on what position WHO has towards using Total coliform as an indication of water contamination we learned that e.coli is considered the most reliable parameter. 

According to CAWST (https://www.cawst.org/): 
> "Total coliforms (TC) were used as an indicator of drinking water since the early 1900s and are commonly used in testing wastewater. However, new research has shown that total coliforms are not useful as an indicator of fecal contamination in drinking water, and they have no sanitary or public health significance (WHO, 2011).

> Originally, total coliforms included four groups of bacteria: Escherichia, Klebsiella, Enterobacter and Citrobacter. These four groups are found in the feces of warm-blooded animals, including humans. However, recent scientific evidence has shown that total coliforms actually include a much broader group of bacteria than the four original groups. In fact, to date there are now 19 recognized groups of bacteria that fall under total coliforms, of which only ten of these groups have actually been associated with feces (BCCDC Environmental Health Laboratory Services, 2006).

> Several groups of bacteria in the environment that are included as total coliforms are associated with soil, vegetation, or water sediments. Therefore, not all total coliforms represent bacteria coming from feces. Recent research has also shown that some groups of total coliforms that are found in animal feces are also capable of multiplying in natural water. This makes it difficult to determine whether the water was contaminated with feces or not.

> Overall, total coliforms should not be used as an indicator of fecal contamination in drinking water. Total coliforms do not meet the two basic criteria for a good indicator organism: 1) to only be associated with the feces of animals, and 2) to not multiply in natural waters.

> CAWST does not recommend using total coliforms as the indicator organism for microbiological testing."

This for us brings the question of what extra value will Total coliform results have for indicating water quality if we already support testing the best possible parameter? Adding Total coliform seems to create more confusion than value to our users (with the information we have today). 

Thus we decided to pause this issue till we hear back from AquagenX on why they added Total coliform to the portfolio.

**Comment by janagombitova** [comment]
Today we clarified a few pending questions around adding Total Coliform (TC) as another test option. 

## How does the test work
- in the field, the test is always done together with testing e.Coli
- you first see the colour change in the bag compartments that indicates the presence of e.Coli and then you shine with the UV light on the bag so see which compartments are light up to indicate the presence of TC 
- if e.Coli is present, then TC is present too --> so you can have a compartment without e.Coli but with TC, but not with TC and without e.Coli

## Why - what is the value of the test
- TC is valuable to screen the success of water treatment
- because you can have cases where e.Coli is not present, but TC still is, this test can indicate if the treatment of the water was sufficient or not 

## New tests 
We decided to keep the existing 2 e.Coli tests as they are and **add two new tests that combine e.Coli + TC**. We have made this decision because: 
- if you do not purchase the UV light, you can still test e.Coli only without being bothered by TC
- when testing TC you always also need to test e.Coli 
- there is no chance to use Aquagenx tests for TC only  

## User workflow for the new tests 
In this case Alphonso will: 
1. Complete the e.Coli steps, click the UI with the compartments to indicate which have a different colour
2. See results and calculated values and risk categories 
3. See a few instructions next for the Total Coliform 
4. Click the UI with the compartments to indicate which have a different colour 
5. See the result MPN value (and not shown in the UI but logged confidence interval) 
6. *optional* summary page with e.coli and total coliform result
7. Go back to Flow where both results are saved. 

We need to ensure that these two new tests work well with Flow and also Lumen's extract transformation

**Comment by janagombitova** [comment]
The workflow is based on changes introduced here: https://github.com/akvo/akvo-caddisfly/issues/243 

# Next steps 
* [x] add two extra tests e.Coli + TC resulting in 4 microbiological tests 
* [x] TC test steps will be added to the second step: 2. Submit result after incubation
* [x] the instructions for e.Coli (step 1)need to be adjusted (remove test bud text in step 3, 4, 8)
* [x] new instructions for TC to be added + images
* [ ] coordinate with Flow and Lumen that the new tests work as expected in all three products 

# Workflow
![New Mockup 1](https://user-images.githubusercontent.com/12456965/62537206-2a6a1300-b850-11e9-8b05-0abe4e124944.png)

**Comment by janagombitova** [comment]
After reviewing the screens I have two suggestions to bring more clarity in the workflow and ensure users see the distinction between what is e.Coli related and what TC related

## 1) Different colour for indicating TC compartments 
When indicating the TC compartments, can we change the colour for the selected areas from the current blue/green to a fluorescent light blue? 

Then the user might better understand that there this is indicating TC and not e.coli as the colour is different from the previous steps and matches more the real colour under the UV light.

## 2) Move Health risk under e.Coli result

In the Results screen: The risk category belongs to e.Coli. Can you push the e.Coli header to the top and more the Health risk category under so it is clear that the risk category is for e.Coli and not TC? Something like this, perhaps: 

<img width="251" alt="Screen Shot 2019-08-27 at 12 05 17" src="https://user-images.githubusercontent.com/12456965/63762740-9fff5700-c8c3-11e9-8ea0-8702cba19676.png">

**Comment by janagombitova** [comment]
After some testing we agreed to change one thing: 

When indicating the TC compartments we now have: 
* already selected e.Coli compartments in grey and not clickable 
* yellow compartments that can be clickable and by selecting them they turn to light blue.

We make the e.Coli compartments not clickable because they by default have TC in them and are counted in the total result. The user is supposed to indicate the **extra** TC compartments. But in cases when there are no extra ones it can be confusing to Alphonso as the e.Coli ones are grey and not selectable, even though they in the actual bag are shining blue. 

So we propose to keep the e.Coli ones not clickable but change the grey to the TC blue. This way Alphonso can see these are counted in for the TC result already.

**Comment by nhternup** [comment]
Changed E.coli compartments (disabled) to blue.
Maybe keeping the number still greyed out may make sense here?

![disabled-blue](https://user-images.githubusercontent.com/4124856/64161293-0acc0780-ce5b-11e9-9413-27738cd261ea.png)

**Comment by janagombitova** [comment]
After a brief back and forth with Mert and Nischal, Mert pointed out that the e.coli compartments will NOT shine bright but remain in their original colour (see image). Thus we will go for keeping them disabled but in their original colour. 

![2](https://user-images.githubusercontent.com/12456965/64163233-25918280-ce41-11e9-9bdc-8e4f09b6cb29.jpg)

**Comment by nhternup** [comment]
Disabled, but remain green:

![disabled-green](https://user-images.githubusercontent.com/4124856/64163818-90ea4d00-ce5f-11e9-8239-765fd5050548.png)
