### ISSUE TITLE
Crash related to Arsenic (0-500) Test

### ISSUE THREAD

**Issue by valllllll2000** [ternup/caddisfly-app#249]
When trying to do the Arsenic 0-500 test on moto g5 ther eis the following crash on the internal test track version :
`Unable to resume activity {org.akvo.caddisfly/org.akvo.caddisfly.sensor.striptest.ui.StripTestActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2, result=-1, data=Intent { cmp=org.akvo.caddisfly/.sensor.striptest.ui.StripMeasureActivity (has extras) }} to activity {org.akvo.caddisfly/org.akvo.caddisfly.sensor.striptest.ui.StripTestActivity}: java.lang.ArrayIndexOutOfBoundsException: length=26; index=27`

**Comment by valllllll2000** [comment]
Note: this crash is already present in the released 275 version

**Comment by nhternup** [comment]
Tracked the cause of the crash to the strip edge/height detection code.

The code looks for the top edge and bottom edge of the strip to determine its height. Sometimes (maybe because of shadows or the texture of the strip), the bottom edge is detected as close to or same as the top edge and height then becomes almost 0.

Will try changing it to begin looking for the bottom edge a few pixels away from the detected top edge as a fix.
