### ISSUE TITLE
Bluetooth connection Lovibond MD610 Photometer with Caddisfly issue

### ISSUE THREAD

**Issue by MBlommestijn** [ternup/caddisfly-app#275]
Unable to connect the Caddisfly app (version: 1.0.19) with the Lovibond MD610 photometer via bluetooth connection.

Normally the Caddisfly app detects the bluetooth signal of the photometer and enables the user to connect the photometer in the photometer questions in the Caddisfly app. During a training all smartphones (4) were not able to connect, the MD610 photometer did not show up in Caddisfly. 

There are currently 64 tests in Caddisfly which require the MD610 photometer bluetooth connection.

**Comment by MBlommestijn** [comment]
Phones that successfully paired with the MD610 photometer:
Android 8 - Huawei Y6
Android 9 - Infinix S5

Phones that did **NOT** pair with the MD610 photometer:
Android 10 - Tecno spark 6 – KE7 
Android 10 - Honor 10 
Android 11 - Samsung Galaxy A 12 
Android 11 - Infinix Note 10 
Android 11 - Sumsung Galaxy S20 FE
Android 11 - OnePlus Nord

**Comment by nhternup** [comment]
Change to location permission to be made as per:

https://developer.android.com/about/versions/10/privacy/changes#location-telephony-bluetooth-wifi
If your app targets Android 10 or higher, it must have the ACCESS_FINE_LOCATION permission in order to use several methods within the Wi-Fi, Wi-Fi Aware, or Bluetooth APIs.
