### ISSUE TITLE
2.5 Preprocess image for calibration phase

### ISSUE THREAD

**Issue by mtwestra** [ternup/caddisfly-app#8]
We need to determine if we need to preprocess the image for the calibration phase. For example, we need to investigate:
1) how to handle gamma correction
2) if we want to correct the global illumination

**Comment by ldporsius** [comment]
It would be good if we can adjust the brightness of the camera to the amount of surrounding light. I mean, when I first start up the camera looking at a dark image, then look to a brighter one, the brighter one is to light. Almost completely white. And vice-versa. I tried to find out how to do this, but nothing so far.

**Comment by mtwestra** [comment]
maybe this helps?

http://stackoverflow.com/questions/21251120/how-should-i-set-exposure-and-white-balance-values-for-custom-camera

In http://developer.android.com/reference/android/hardware/Camera.Parameters.html there are a number of things related to the exposure, notably this one:

http://developer.android.com/reference/android/hardware/Camera.Parameters.html#setAutoExposureLock(boolean)

This might also be relevant:
To make camera parameters take effect, applications have to call setParameters(Camera.Parameters). For example, after setWhiteBalance(String) is called, white balance is not actually changed untilsetParameters(Camera.Parameters) is called with the changed parameters object.

**Comment by ldporsius** [comment]
![device-2015-07-10-172214](https://cloud.githubusercontent.com/assets/9623423/8621860/3c52cfca-2728-11e5-8917-5cd826b13790.png)

This is the result of today's work. The picture was taken indoors with no artificial light source and with the blinds down. So illumination is not bright, but also no high contrast between shadow and light.

You can see that there are four finder patterns in this sample. If you like, please pay attention to the white in the image. I applied a filter hoping to enhance contrast and another one to sharpen.

Please let me draw your attention to the calibration square bottom second from left. You can see that it is a 'white' but not as white as the paper it is printed on. So do you think that gives an indication about the quality of this result?

Now please take a look at the large black rectangle. That is where our strip is going to be. You may see that the black is evenly distributed in the rectangle. This I think could be of importance, if we want to detect an overall lighter color to detect our strip. We cannot permit our self to turn more 'white' because of illumination. I am talking about retinex.

http://www.ipol.im/pub/art/2011/lmps_rpe/?utm_source=doi

Human brain sees black but computer does not, in a nuttshell. Therefore I think is is important that our black is _black_. Sorry can't explain so well.

**Comment by ldporsius** [comment]
@mtwestra To clearify: this is I think what you mean by 

2) if we want to correct the global illumination

**Comment by ldporsius** [comment]
My findings are that the standard Android camera adjusts it's exposure automatically. I mean, the most basic instance of Camera compensates for brightness of external light. If you point it at a sunny spot in the distance, the foreground gets dark. Do you understand what I mean? Sorry if I cannot explain in photographer's parlay. Maybe it is just a thing  _not_ to interfere with that?
Anyway, because of this standard behavior, if one or more of the finder patterns are extremely dark or bright, code won't detect them. So that helps us already.

**Comment by mtwestra** [comment]
This is now part of the calibration phase.
